### ISSUE TITLE
Исправил readme в 1,2,3 лабах. добавил given when then в тестах

### ISSUE THREAD

**Issue by Tart1lya** [Tart1lya/labs_asd#1]
@anton0afanasiev0v Здравствуйте, исправил readme в 1,2,3 лабах (добавил навигацию). добавил given when then в тестах

**Comment by anton0afanasiev0v** [comment]
Есть мелкие замечания, делай следующие лабы

**Comment by Tart1lya** [comment]
@anton0afanasiev0v а мне с этими лабами приходить на защиту?

**Comment by anton0afanasiev0v** [comment]
да + делай следующие лабы
